# ============================================
# Codecov Configuration
# ============================================

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "**/*.test.js"
  - "coverage/**/*"
  - "scripts/**/*"
